# Generated by Django 4.2.1 on 2023-06-02 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=64, unique=True)),
                ('rok_produkcji', models.PositiveSmallIntegerField()),
                ('opis', models.TextField(default='')),
                ('premiera', models.DateField(blank=True, null=True)),
                ('oceny', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('w_sprzedazy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzja', models.TextField(blank=True, default='')),
                ('gwiazdki', models.PositiveSmallIntegerField(default=5)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auta.auto')),
            ],
        ),
        migrations.CreateModel(
            name='Model_auta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojemnosc', models.CharField(max_length=32)),
                ('konie_mechaniczne', models.CharField(max_length=32)),
                ('auto', models.ManyToManyField(to='auta.auto')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('przebieg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nadwozie', models.PositiveSmallIntegerField(blank=True, choices=[(3, 'sedan'), (1, 'Hatchback'), (0, 'pick-up'), (2, 'combi'), (4, 'kabriolet'), (5, 'coupe'), (6, 'roadster')], null=True)),
                ('punkty_kierowcow', models.PositiveSmallIntegerField(default=0)),
                ('auto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auta.auto')),
            ],
        ),
    ]
