# Generated by Django 4.2.1 on 2023-06-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0003_alter_extrainfo_nadwozie'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='model',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='nadwozie',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'sedan'), (4, 'kabriolet'), (1, 'Hatchback'), (5, 'coupe'), (0, 'pick-up'), (6, 'roadster'), (2, 'combi')], null=True),
        ),
    ]
