# Generated by Django 4.2.1 on 2023-06-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auta', '0004_auto_model_alter_extrainfo_nadwozie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='nadwozie',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'coupe'), (4, 'kabriolet'), (0, 'pick-up'), (3, 'sedan'), (2, 'combi'), (6, 'roadster'), (1, 'Hatchback')], null=True),
        ),
    ]
